FROM python:3.8

RUN pip install \
    ansible==2.9.9 \
    netmiko==3.1.1 \
    ncclient==0.6.7 \
    paramiko==2.7.1 \
    jinja2==2.10.3 \
    markupsafe==1.1.1

WORKDIR /app

CMD ["/bin/bash"]