- name: Router Test
  hosts: cisco
  gather_facts: no
  

  tasks:
    - name: Show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: version

    - debug:
        var: version.stdout[0]